### ISSUE TITLE
Add to the docs a list of categories only

### ISSUE THREAD

**Issue by zoffixznet** [EnlightenedPerlOrganisation/task-kensho#12]
Hey,

It would be nice if the docs had a section listing all the available `Task::Kensho::*` categories. Essentially a list like this, but with the one-two word descriptions: 
![kensho-list](https://cloud.githubusercontent.com/assets/5747918/6636824/2cea4c84-c94a-11e4-9702-d928e99a1148.png)

Last night I was browsing the module, looking for anything recommended for RESTful communications, and it was tough figuring out what sections Kensho even covers. I ended up scrolling through a giant TOC:

![kensho](https://cloud.githubusercontent.com/assets/5747918/6636878/83530110-c94a-11e4-966c-97a8b0fea77d.png)

I think a list of sections in the docs would be beneficial.

**Comment by karenetheridge** [comment]
PR #45 is now merged. thanks for the feedback.
