### ISSUE TITLE
Dancer should be Dancer2

### ISSUE THREAD

**Issue by rleir** [EnlightenedPerlOrganisation/task-kensho#13]
I think Dancer2 is ready for prime time. What do you think?

**Comment by basbloemsaat** [comment]
Yup, think so too!

**Comment by karenetheridge** [comment]
@xsawyerx comments?

**Comment by xsawyerx** [comment]
@karenetheridge missed this among my emails. Yes, please.

**Comment by rleir** [comment]
PR #17  just promotes to Dancer2
Thanks!
