### ISSUE TITLE
Add Moo to OOP section

### ISSUE THREAD

**Issue by haarg** [EnlightenedPerlOrganisation/task-kensho#14]
This has been proposed a number of times, but I believe the decision was to hold off on adding it until the situation with strictures/fatal warnings was resolved.  That has been resolved for a year or so now, so it would be good to add it.

**Comment by karenetheridge** [comment]
I'd be happy to see both Moo and Moose added, and Task::Moose removed (since it contains a lot of old crufty things).

**Comment by karenetheridge** [comment]
and namespace::autoclean for support

**Comment by karenetheridge** [comment]
I vote yes.

**Comment by perigrin** [comment]
I vote yes.

**Comment by haarg** [comment]
+1
