### ISSUE TITLE
Replace Task::Moose with hand picked selection of modules

### ISSUE THREAD

**Issue by haarg** [EnlightenedPerlOrganisation/task-kensho#15]
This was proposed by @karenetheridge on IRC, so I'm creating a issue for discussion.

The Task::Moose module is rather huge, and includes some modules that we may not want to recommend generally.  It might be better to hand pick a selection of modules for that section rather than just pointing to the more inclusive bundle.

**Comment by karenetheridge** [comment]
how about:

* Moose
* Moo
* namespace::autoclean
* MooseX::Getopt
* MooseX::SimpleConfig
* MooseX::Aliases
* MooseX::StrictConstructor
* MooseX::NonMoose
* MooseX::Role::Parameterized
* MooX::...?

**Comment by haarg** [comment]
I think we'd want either MooseX::Types or Type::Tiny.

I don't have any strong opinions on MooX modules that would be sensible to include.

**Comment by karenetheridge** [comment]
Maybe Package::Variant, to go along with MXRP.

**Comment by karenetheridge** [comment]
I vote yes, and propose this list:

* Moose
* Moo
* namespace::autoclean
* MooseX::Getopt
* MooseX::SimpleConfig
* MooseX::Aliases
* MooseX::StrictConstructor
* MooseX::NonMoose
* MooseX::Role::Parameterized
* Type::Tiny
* Package::Variant

**Comment by perigrin** [comment]
I vote yes but would like to see `Task::Moose` made to be non-problematic.

**Comment by karenetheridge** [comment]
> would like to see Task::Moose made to be non-problematic.

Good idea! I see I have comaint so I could see about trying to fix that up a bit. Presently its issues list is empty: https://rt.cpan.org/Dist/Display.html?Name=Task-Moose

**Comment by haarg** [comment]
+1 to @karenetheridge's list.  We should keep a link to Task::Moose in the docs though, and get that cleaned up and updated too.

**Comment by haarg** [comment]
Task::Moose didn't end up getting removed.  To clarify my earlier comment, I'd like for it to be in the docs in some form, but not part of the main list or in the prereqs.

**Comment by karenetheridge** [comment]
> To clarify my earlier comment, I'd like for it to be in the docs in some form, but not part of the main list or in the prereqs.

Ah, I misunderstood!
Do you have a suggestion for how it could be mentioned in the docs?

**Comment by haarg** [comment]
Possibly in the description for Moose as "also see Task::Moose for a larger list of Moose extensions"
