### ISSUE TITLE
remove Test::Most

### ISSUE THREAD

**Issue by karenetheridge** [EnlightenedPerlOrganisation/task-kensho#19]
It is mostly just a bundle of other Test::* modules, but also tinkers with test guts in naughty ways (e.g. see https://rt.cpan.org/Ticket/Display.html?id=100213). We are better off recommending individual test modules, and CPAN distributions benefit from having fewer dependencies.

(I vote yes)

**Comment by perigrin** [comment]
I vote yes

**Comment by haarg** [comment]
+1
