### ISSUE TITLE
replace Test::NoWarnings with Test::Warnings

### ISSUE THREAD

**Issue by karenetheridge** [EnlightenedPerlOrganisation/task-kensho#20]
Test::Warnings was written to be a drop-in replacement for Test::NoWarnings that also allows one to use `done_testing` without running into plan issues; it also covers the interfaces provided by Test::Warn (which Test::Most dragged in).

I'm mostly indifferent as to whether Test::FailWarnings is also included (as in PR#3).

(I vote yes on the first paragraph.)

**Comment by karenetheridge** [comment]
I also found this in my irc logs from a while back:

```
10:40 < ether> I'd also remove Test::NoWarnings, as its usecases are becoming extremely limited in comparison to the alternatives now
10:41 < ether> I wrote Test::Warnings a few years ago out of frustration
10:44 < osfameron> good idea
```

**Comment by perigrin** [comment]
I vote yes.

**Comment by haarg** [comment]
+1
