### ISSUE TITLE
add Web::Simple to WebDev

### ISSUE THREAD

**Issue by karenetheridge** [EnlightenedPerlOrganisation/task-kensho#21]
(I vote yes)

**Comment by ttkciar** [comment]
This seems to occupy the same niche as Dancer2, minus the Moose heaviness.

I'm intrigued, but also unsure.  Are there compelling reasons to advocate Web::Simple over Dancer2?

(Going to kick its tires this weekend and hopefully answer my own question)

**Comment by Grinnz** [comment]
Both of them use Moo actually but what it doesn't do is most of the "framework" part. All it does by default is dispatch responses to requests.

**Comment by Grinnz** [comment]
https://shadow.cat/blog/matt-s-trout/mstpan-1/#web::simple

**Comment by ttkciar** [comment]
Oops, you're right, just noticed my mistake and popped back here to edit my post, but you're too fast for me.

Web::Simple is an mst production, which is enough to make me give it a thorough going-over.  He consistently publishes useful stuff.

**Comment by ttkciar** [comment]
The question I will investigate is: Is there a compelling reason to use Web::Simple as opposed to that subset of Dancer2 which is functionally equivalent to Web::Simple?

**Comment by ttkciar** [comment]
Web::Simple has a slightly more powerful dispatch specification interface than Dancer2, and a much smaller mass of module dependencies.  Performance seems about the same.  Dancer2 of course has a lot more framework'ish features, but that is irrelevant to the proposal.

All in all, a nifty library.  It is well documented and easy to use.  Kudos to mst.

I support the proposal to add Web::Simple to WebDev.

**Comment by karenetheridge** [comment]
fixed with #73.
