### ISSUE TITLE
Task::Kensho::XML requires Perl 5.14 due to RDF::Trine dependency on IRI

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#29]
Several other subtasks require 5.10 for various dependencies but this is the only subtask that ends up requiring higher than that.

**Comment by karenetheridge** [comment]
We could note this in the docs, but I don't think we should add anything to metadata, as downstream dependencies' requirements could change at any time.

**Comment by Grinnz** [comment]
Possible alternative could be RDF::Trine could be a dynamic dependency for perl 5.14+?

**Comment by perigrin** [comment]
I’m also sure that kasei would accept a patch if possible to downport IRI.

**Comment by perigrin** [comment]
Talking with #perlrdf on irc.perl.org, I think the right answer is to replace RDF::Trine with Attean and maybe do a dynamic dependency where it only shows up on 5.14+ (like @Grinnz was suggesting)

**Comment by kjetilk** [comment]
Indeed! So, the [Attean](https://github.com/kasei/attean) framework is filled with the lessons learned over the years, both based on our work with RDF, but also our interaction with Enlightened hackers. It is a framework built with Moo and roles throughout. Attean and RDF::Trine are written by the same people, so Attean is the official successor of RDF::Trine.

It is fairly complete, in the sense that the framework does what we want from it, but it is a bit lacking in terms of documentation, implementations of things like data stores. Also, there is quite a lot of RDF code that hasn't been ported yet. 

We hope that users will adopt Attean, so it is indeed really great to see that in Task::Kensho.

**Comment by Grinnz** [comment]
Due to https://metacpan.org/release/GWILLIAMS/IRI-0.009 this should be resolved, thanks @kasei.
