### ISSUE TITLE
Replace Devel::Repl with Reply

### ISSUE THREAD

**Issue by perigrin** [EnlightenedPerlOrganisation/task-kensho#31]
Received via Email:

> Hi Chris,
> 
> I see that Task::Kensho recommends using Devel::Repl.  I had some trouble installing this tool and 
> did some searching online and I found that the author of that tool appears to recommend a different 
> repl called Reply.  See for details: https://shadow.cat/blog/matt-s-trout/mstpan-17/
> 
> That being the case, perhaps an update to Task::Kensho is in order?
> 
> Thank you.
> 
> Regards,
> Rich Duzenbury

**Comment by stphnlyd** [comment]
I would like to see both Reply and Devel::REPL on the list. Each has its strength.
