### ISSUE TITLE
Remove Perl::Version

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#38]
Perl::Version does not actually deal with Perl-style versions, it only correctly works with version tuples which is one of the two Perl version styles (and the less prevalent one at that). See: https://rt.cpan.org/Ticket/Display.html?id=110074, https://rt.cpan.org/Ticket/Display.html?id=114541, https://rt.cpan.org/Ticket/Display.html?id=119447, https://rt.cpan.org/Ticket/Display.html?id=124070, https://rt.cpan.org/Ticket/Display.html?id=54481, https://rt.cpan.org/Ticket/Display.html?id=47501

Modern authors should not need any module to deal with Perl versions of either format since version.pm is used automatically. Version::Next can be used for correct version bumping.

**Comment by stphnlyd** [comment]
+1

the core "version" module should always be used for this purpose.
