### ISSUE TITLE
Add Syntax::Keyword::Try to Exceptions category

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#39]
The new best-in-class for exception handling. I know, this means my previous issue of a module that requires Perl 5.14 will be present, but it's worth it here.

**Comment by karenetheridge** [comment]
I'm not bothered much by some modules requiring 5.14.  Half the purpose of TK's existence is for documentation, and for the other half, the user can still get everything else even if one of the prereqs fails to install.

**Comment by stphnlyd** [comment]
I dont think it is a problem if something requires 5.14. actually I would argue that people should use at least 5.14 for modern perl development.
