### ISSUE TITLE
Add Future to Async category

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#53]
Future is a great eventloop-independent tool for async programming.

**Comment by leonerd** [comment]
I'd hold off on the `IO::Async` part quite yet; I'm still working on `Future::IO` which might end up being a better abstraction API for "small modules" - the sorts of things that want to mostly just be self-contained synchronous stuff but leave open the option of being async and concurrent with other stuff if the end-user wishes, but the module author isn't forced into.

**Comment by karenetheridge** [comment]
fixed with #72.
