### ISSUE TITLE
Add Test2::Suite to Testing category

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#54]

**Comment by abraxxa** [comment]
Adding is ok but not recommending it for now as we tried to use it in our CI and it failed quite often which made us switch back to ‚make test‘.

**Comment by Grinnz** [comment]
Could you elaborate? Test2::Suite is a replacement for Test::More, not make test.

**Comment by karenetheridge** [comment]
fixed with #64.
