### ISSUE TITLE
Add parallelization modules to Async category

### ISSUE THREAD

**Issue by Grinnz** [EnlightenedPerlOrganisation/task-kensho#58]
Possible candidates: MCE, Parallel::ForkManager, IO::Async::Function (though redundant with IO::Async already there)

Ref: #10 #56

**Comment by PaulGWebster** [comment]
Shoudl be restricted to things that can run on the three largest consumers of perl: BSD, Linux and Windows.

**Comment by karenetheridge** [comment]
fixed with #72.
