### ISSUE TITLE
Recommend a JSON Module.

### ISSUE THREAD

**Issue by perigrin** [EnlightenedPerlOrganisation/task-kensho#8]
We should probably add JSON::MaybeXS to the recommended modules.

**Comment by karenetheridge** [comment]
+1 :)

**Comment by ranguard** [comment]
+1 :)

**Comment by perigrin** [comment]
I make my implicit vote explicit.

**Comment by karenetheridge** [comment]
w00t, we're at 3 votes...

How about, in the Config section: "wrapper around the most current and fast JSON backends"
